name: dingo_clean
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cached_network_image: ^3.2.0
  cloud_firestore: ^3.1.11
  country_icons: ^2.0.2
  date_picker_timeline: ^1.2.3
  dropdown_button2: ^1.2.2
  fdottedline_nullsafety: ^2.0.0
  firebase_auth: ^3.3.13
  fl_chart: ^0.50.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_masked_text: ^0.8.0
  flutter_scale_tap: ^1.0.5
  flutter_spinkit: ^5.1.0
  font_awesome_flutter: ^10.1.0
  iconsax: ^0.0.8
  infinite_carousel: ^1.0.2
  lottie: ^1.2.2
  material_floating_search_bar: ^0.3.6
  pin_code_fields: ^7.3.0
  scrollable_positioned_list: ^0.2.3
  simple_animations: ^4.0.1
  url_launcher: ^6.0.20
  js: ^0.6.2
  firebase_core: ^1.14.0
  image_picker: ^0.8.5
  firebase_storage: ^10.2.12
  easy_localization: ^3.0.0
  flutter_stripe: ^2.5.0
  http: ^0.13.4
  get: ^4.6.1
  flutter_braintree: ^2.3.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/images/house_type/
