name: dingo_clean
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cached_network_image: ^3.2.0
  country_icons: ^2.0.2
  date_picker_timeline: ^1.2.3
  fdottedline_nullsafety: ^2.0.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_scale_tap: ^1.0.5
  flutter_spinkit: ^5.1.0
  iconsax: ^0.0.8
  infinite_carousel: ^1.0.2
  lottie: ^1.2.2
  material_floating_search_bar: ^0.3.6
  pin_code_fields: ^7.3.0
  scrollable_positioned_list: ^0.2.3
  simple_animations: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
